# Generated by Django 6.0.4 on 2026-05-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='hrms.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('employee_type', models.CharField(choices=[('IC', 'Individual Contributor'), ('MM', 'Middle Management'), ('SL', 'Senior Leadership'), ('CS', 'C-Suite')], default='IC', max_length=2)),
                ('level', models.CharField(choices=[('L1', 'L1 – Associate'), ('L2', 'L2 – Junior'), ('L3', 'L3 – Mid-Level'), ('L4', 'L4 – Senior IC'), ('SPM', 'Senior Product Manager'), ('GM', 'Group Manager'), ('DIR', 'Director'), ('SVP', 'Senior Vice President'), ('VP', 'Vice President'), ('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('CTO', 'Chief Technology Officer'), ('COO', 'Chief Operating Officer')], default='L1', max_length=5)),
                ('hire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrms.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hrms.employee')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLAN', 'Planning'), ('ACTIVE', 'Active'), ('HOLD', 'On Hold'), ('DONE', 'Completed'), ('CANC', 'Cancelled')], default='PLAN', max_length=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='hrms.department')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='hrms.employee')),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to='hrms.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
