# Generated by Django 6.0.4 on 2026-05-04 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuseumTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhoods', to='poi.city')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('poi_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('museum', 'Museum'), ('government', 'Government'), ('bank', 'Bank')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_of_interest', to='poi.neighbourhood')),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
            },
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_exhibition', models.CharField(blank=True, max_length=300)),
                ('permanent_collection', models.TextField(blank=True)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_free', models.BooleanField(default=False)),
                ('founding_year', models.PositiveIntegerField(blank=True, null=True)),
                ('num_floors', models.PositiveSmallIntegerField(default=1)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='museums', to='poi.museumtheme')),
                ('poi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='museum', to='poi.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('federal', 'Federal'), ('state', 'State / Provincial'), ('municipal', 'Municipal')], default='municipal', max_length=20)),
                ('official_name', models.CharField(blank=True, max_length=200)),
                ('services_offered', models.TextField(blank=True)),
                ('appointment_required', models.BooleanField(default=False)),
                ('public_access', models.BooleanField(default=True)),
                ('poi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='government', to='poi.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_type', models.CharField(choices=[('commercial', 'Commercial Bank'), ('credit_union', 'Credit Union'), ('investment', 'Investment Bank'), ('central', 'Central Bank'), ('savings', 'Savings Bank')], default='commercial', max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=11)),
                ('has_atm', models.BooleanField(default=True)),
                ('num_atms', models.PositiveSmallIntegerField(default=1)),
                ('drive_through', models.BooleanField(default=False)),
                ('accepts_foreign_currency', models.BooleanField(default=False)),
                ('poi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='poi.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_capacity', models.PositiveIntegerField(default=0)),
                ('price_range', models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('$$$$', '$$$$')], default='$$', max_length=10)),
                ('has_delivery', models.BooleanField(default=False)),
                ('has_takeout', models.BooleanField(default=False)),
                ('michelin_stars', models.PositiveSmallIntegerField(default=0)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='poi.cuisine')),
                ('poi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='poi.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='NearbyPOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk_minutes', models.PositiveSmallIntegerField(default=5)),
                ('from_poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_from', to='poi.pointofinterest')),
                ('to_poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_to', to='poi.pointofinterest')),
            ],
            options={
                'verbose_name_plural': 'Nearby POIs',
                'unique_together': {('from_poi', 'to_poi')},
            },
        ),
    ]
